name: Test workflow

on:
  # manual only
  workflow_dispatch:
  pull_request:


jobs:
  lint-action:
    runs-on: ubuntu-latest
    name: Lint action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: make lint

  test-github-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v4
      with:
        persist-credentials: false
                       
    - name: Test 
      uses: opensafely-core/update-dependencies-action@main
      with: 
        update_command: "echo updated > update.txt"
        on_changes_command: "echo changed > on_changes.txt"
        automerge: false
  